# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Feb 24 02:34:43 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1202, 603)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(200, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/heidi.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.databaseTree = QtGui.QTreeWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databaseTree.sizePolicy().hasHeightForWidth())
        self.databaseTree.setSizePolicy(sizePolicy)
        self.databaseTree.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.databaseTree.setBaseSize(QtCore.QSize(350, 0))
        self.databaseTree.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.databaseTree.setRootIsDecorated(False)
        self.databaseTree.setUniformRowHeights(True)
        self.databaseTree.setHeaderHidden(True)
        self.databaseTree.setColumnCount(1)
        self.databaseTree.setObjectName(_fromUtf8("databaseTree"))
        self.databaseTree.headerItem().setText(0, _fromUtf8("1"))
        self.twMachineTabs = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twMachineTabs.sizePolicy().hasHeightForWidth())
        self.twMachineTabs.setSizePolicy(sizePolicy)
        self.twMachineTabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.twMachineTabs.setObjectName(_fromUtf8("twMachineTabs"))
        self.machineTab = QtGui.QWidget()
        self.machineTab.setObjectName(_fromUtf8("machineTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.machineTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.processListTab = QtGui.QTabWidget(self.machineTab)
        self.processListTab.setObjectName(_fromUtf8("processListTab"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.processListTree = QtGui.QTreeWidget(self.tab)
        self.processListTree.setObjectName(_fromUtf8("processListTree"))
        self.verticalLayout_4.addWidget(self.processListTree)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/resultset_next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.processListTab.addTab(self.tab, icon1, _fromUtf8(""))
        self.hostTabDB = QtGui.QWidget()
        self.hostTabDB.setObjectName(_fromUtf8("hostTabDB"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.hostTabDB)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableWidget = QtGui.QTableWidget(self.hostTabDB)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/database.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.processListTab.addTab(self.hostTabDB, icon2, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.processListTab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/computer.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.twMachineTabs.addTab(self.machineTab, icon3, _fromUtf8(""))
        self.databaseTab = QtGui.QWidget()
        self.databaseTab.setObjectName(_fromUtf8("databaseTab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.databaseTab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.databaseInfoTable = QtGui.QTableWidget(self.databaseTab)
        self.databaseInfoTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.databaseInfoTable.setAlternatingRowColors(False)
        self.databaseInfoTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.databaseInfoTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.databaseInfoTable.setCornerButtonEnabled(False)
        self.databaseInfoTable.setObjectName(_fromUtf8("databaseInfoTable"))
        self.databaseInfoTable.setColumnCount(8)
        self.databaseInfoTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.databaseInfoTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.databaseInfoTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.databaseInfoTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.databaseInfoTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.databaseInfoTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.databaseInfoTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.databaseInfoTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.databaseInfoTable.setHorizontalHeaderItem(7, item)
        self.databaseInfoTable.horizontalHeader().setDefaultSectionSize(80)
        self.databaseInfoTable.horizontalHeader().setHighlightSections(False)
        self.databaseInfoTable.horizontalHeader().setMinimumSectionSize(50)
        self.databaseInfoTable.horizontalHeader().setStretchLastSection(True)
        self.databaseInfoTable.verticalHeader().setVisible(False)
        self.databaseInfoTable.verticalHeader().setDefaultSectionSize(20)
        self.databaseInfoTable.verticalHeader().setMinimumSectionSize(15)
        self.horizontalLayout.addWidget(self.databaseInfoTable)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/database.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.twMachineTabs.addTab(self.databaseTab, icon4, _fromUtf8(""))
        self.txtStatus = QtGui.QTextEdit(self.splitter_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtStatus.setFont(font)
        self.txtStatus.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txtStatus.setObjectName(_fromUtf8("txtStatus"))
        self.verticalLayout.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1202, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSession_Manager = QtGui.QAction(MainWindow)
        self.actionSession_Manager.setObjectName(_fromUtf8("actionSession_Manager"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionRefresh = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/arrow_refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon5)
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))
        self.menuFile.addAction(self.actionSession_Manager)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionRefresh)

        self.retranslateUi(MainWindow)
        self.twMachineTabs.setCurrentIndex(1)
        self.processListTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "pyHeidi", None, QtGui.QApplication.UnicodeUTF8))
        self.processListTree.setSortingEnabled(True)
        self.processListTree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "id", None, QtGui.QApplication.UnicodeUTF8))
        self.processListTree.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.processListTree.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Host", None, QtGui.QApplication.UnicodeUTF8))
        self.processListTree.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "DB", None, QtGui.QApplication.UnicodeUTF8))
        self.processListTree.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "Command", None, QtGui.QApplication.UnicodeUTF8))
        self.processListTree.headerItem().setText(5, QtGui.QApplication.translate("MainWindow", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.processListTree.headerItem().setText(6, QtGui.QApplication.translate("MainWindow", "State", None, QtGui.QApplication.UnicodeUTF8))
        self.processListTree.headerItem().setText(7, QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.processListTab.setTabText(self.processListTab.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Processes", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Items", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Last Modification", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Tables", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "Views", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("MainWindow", "Functions", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("MainWindow", "Procedures", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("MainWindow", "Triggers", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("MainWindow", "Events", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(QtGui.QApplication.translate("MainWindow", "Default Collation", None, QtGui.QApplication.UnicodeUTF8))
        self.processListTab.setTabText(self.processListTab.indexOf(self.hostTabDB), QtGui.QApplication.translate("MainWindow", "Databases (0)", None, QtGui.QApplication.UnicodeUTF8))
        self.twMachineTabs.setTabText(self.twMachineTabs.indexOf(self.machineTab), QtGui.QApplication.translate("MainWindow", "Host: ", None, QtGui.QApplication.UnicodeUTF8))
        self.databaseInfoTable.setSortingEnabled(True)
        item = self.databaseInfoTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        item = self.databaseInfoTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Rows", None, QtGui.QApplication.UnicodeUTF8))
        item = self.databaseInfoTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        item = self.databaseInfoTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Created", None, QtGui.QApplication.UnicodeUTF8))
        item = self.databaseInfoTable.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Updated", None, QtGui.QApplication.UnicodeUTF8))
        item = self.databaseInfoTable.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "Engine", None, QtGui.QApplication.UnicodeUTF8))
        item = self.databaseInfoTable.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("MainWindow", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        item = self.databaseInfoTable.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.twMachineTabs.setTabText(self.twMachineTabs.indexOf(self.databaseTab), QtGui.QApplication.translate("MainWindow", "Database: ", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSession_Manager.setText(QtGui.QApplication.translate("MainWindow", "Session Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setShortcut(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
